FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /src

COPY Directory.Build.props ./
COPY StyleCop.ruleset ./
COPY stylecop.json ./
COPY tests/e2e/NexusTeam.E2E.Tests/NexusTeam.E2E.Tests.csproj ./tests/e2e/NexusTeam.E2E.Tests/

RUN dotnet restore tests/e2e/NexusTeam.E2E.Tests/NexusTeam.E2E.Tests.csproj

COPY tests/e2e/NexusTeam.E2E.Tests/ ./tests/e2e/NexusTeam.E2E.Tests/
COPY tests/e2e/run-e2e-tests.sh ./tests/e2e/run-e2e-tests.sh

CMD ["sh", "tests/e2e/run-e2e-tests.sh"]
